apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-todos
  labels:
    app: simple-todos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-todos
  template:
    metadata:
      labels:
        app: simple-todos
    spec:
      containers:
      - name: simple-todos
        image: darksinge/simple-todos
        imagePullPolicy: Always
        env:
        - name: REDIS_HOST
          value: "redis-svc"
        envFrom:
          - secretRef:
              name: simple-todos-secret
        ports:
        - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:6.0.6-alpine
        env:
          - name: MASTER
            value: "true"
        resources:
          limits:
            memory: "250Mi"
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-svc
spec:
  selector:
    app: redis
  ports:
    - name: http
      protocol: TCP
      port: 6379
      targetPort: 6379